### ISSUE TITLE
The CI does not test the function before or after deploying

### ISSUE THREAD

**Issue by HarvsG** [HarvsG/r-SpaceX-AI-Bot#2]
```
deploy:
  - provider: script
    script:
      # change FUNCTION_NAME PROJECT and REPO to the values from the cloud console: https://console.cloud.google.com/code/develop. Note function name is from your main file, usualy index.js, the main function exports.FUNCTION_NAME
      - gcloud --quiet beta functions deploy SpaceXFulfillment --source-url https://source.developers.google.com/p/r-spacex-ai/r/r-SpaceX-AI-google-source-repo --source-path / --trigger-http
      #- gcloud beta functions call SpaceXFulfillment --file=requestExample.json # NOT working, it would be good to emulate and test the function and then only deploy if successful!
   
```
`functions call SpaceXFulfillment --file=requestExample.json`
should, in theory, test the function, it would be great to make deployment conditional on the outcome of that.

Edit: `--file` is not a valid flag
